### ISSUE TITLE
MVP / Milestone definitions / Technical base

### ISSUE THREAD

**Issue by FranzSkuffka** [FranzSkuffka/jibba#1]
- [ ] _MVP: A list of rides from A to B, no geolocation services. Simple contact information for each ride. No status what so ever.
- [ ] Geo-Based search for finding rides that could be shared with you.
  - use Gmaps directions API to generate routes for each route. 
  - use outer bounds to search for close points. incorporate route characteristics
- [ ] Opt-in and community-penalized opt-out. Possibly share a few words why you get this ride so the threshold for commiting is higher
